// Generated by scripts/generate-database-types.mjs from the isolated local Supabase stack. Do not edit.
// Regenerate after any migration change: npm run db:types (requires this checkout's local stack).
// migrations-sha256: 3de3d80004509577c654c5a2f5783cf7512231f6314a5da15a1ca7ad5cca1809
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      admin_audit_events: {
        Row: {
          action: string
          actor_user_id: string | null
          created_at: string
          entity_id: number | null
          entity_type: string
          id: number
          metadata: Json
        }
        Insert: {
          action: string
          actor_user_id?: string | null
          created_at?: string
          entity_id?: number | null
          entity_type: string
          id?: never
          metadata?: Json
        }
        Update: {
          action?: string
          actor_user_id?: string | null
          created_at?: string
          entity_id?: number | null
          entity_type?: string
          id?: never
          metadata?: Json
        }
        Relationships: []
      }
      admin_profiles: {
        Row: {
          created_at: string
          display_name: string | null
          email: string
          is_active: boolean
          role: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          email: string
          is_active?: boolean
          role: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          email?: string
          is_active?: boolean
          role?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      article_blocks: {
        Row: {
          archived_at: string | null
          article_id: number
          block_type: string
          content: Json
          created_at: string
          created_by: string | null
          id: number
          linked_project_id: number | null
          linked_stone_group_id: number | null
          media_asset_id: number | null
          published_at: string | null
          sort_order: number
          status: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          article_id: number
          block_type: string
          content?: Json
          created_at?: string
          created_by?: string | null
          id?: never
          linked_project_id?: number | null
          linked_stone_group_id?: number | null
          media_asset_id?: number | null
          published_at?: string | null
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          article_id?: number
          block_type?: string
          content?: Json
          created_at?: string
          created_by?: string | null
          id?: never
          linked_project_id?: number | null
          linked_stone_group_id?: number | null
          media_asset_id?: number | null
          published_at?: string | null
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "article_blocks_article_id_fkey"
            columns: ["article_id"]
            isOneToOne: false
            referencedRelation: "articles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "article_blocks_linked_project_id_fkey"
            columns: ["linked_project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "article_blocks_linked_stone_group_id_fkey"
            columns: ["linked_stone_group_id"]
            isOneToOne: false
            referencedRelation: "stone_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "article_blocks_media_asset_id_fkey"
            columns: ["media_asset_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
        ]
      }
      articles: {
        Row: {
          archived_at: string | null
          author: string | null
          cover_media_id: number | null
          created_at: string
          created_by: string | null
          excerpt: string | null
          id: number
          legacy_source_path: string | null
          legacy_source_url: string | null
          published_at: string | null
          published_on: string | null
          seo: Json
          slug: string
          sort_order: number
          status: string
          tags: string[]
          title: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          author?: string | null
          cover_media_id?: number | null
          created_at?: string
          created_by?: string | null
          excerpt?: string | null
          id?: never
          legacy_source_path?: string | null
          legacy_source_url?: string | null
          published_at?: string | null
          published_on?: string | null
          seo?: Json
          slug: string
          sort_order?: number
          status?: string
          tags?: string[]
          title: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          author?: string | null
          cover_media_id?: number | null
          created_at?: string
          created_by?: string | null
          excerpt?: string | null
          id?: never
          legacy_source_path?: string | null
          legacy_source_url?: string | null
          published_at?: string | null
          published_on?: string | null
          seo?: Json
          slug?: string
          sort_order?: number
          status?: string
          tags?: string[]
          title?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "articles_cover_media_id_fkey"
            columns: ["cover_media_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
        ]
      }
      enquiries: {
        Row: {
          assigned_to: string | null
          company: string | null
          created_at: string
          email: string
          id: number
          internal_notes: string | null
          message: string | null
          name: string
          notification_status: string
          phone: string | null
          project_type: string | null
          source_route: string | null
          status: string
          turnstile_success: boolean | null
          updated_at: string
        }
        Insert: {
          assigned_to?: string | null
          company?: string | null
          created_at?: string
          email: string
          id?: never
          internal_notes?: string | null
          message?: string | null
          name: string
          notification_status?: string
          phone?: string | null
          project_type?: string | null
          source_route?: string | null
          status?: string
          turnstile_success?: boolean | null
          updated_at?: string
        }
        Update: {
          assigned_to?: string | null
          company?: string | null
          created_at?: string
          email?: string
          id?: never
          internal_notes?: string | null
          message?: string | null
          name?: string
          notification_status?: string
          phone?: string | null
          project_type?: string | null
          source_route?: string | null
          status?: string
          turnstile_success?: boolean | null
          updated_at?: string
        }
        Relationships: []
      }
      finish_definitions: {
        Row: {
          archived_at: string | null
          created_at: string
          created_by: string | null
          description: string | null
          display_name: string
          finish_key: string
          id: number
          published_at: string | null
          sort_order: number
          status: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          display_name: string
          finish_key: string
          id?: never
          published_at?: string | null
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          display_name?: string
          finish_key?: string
          id?: never
          published_at?: string | null
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      image_qr_resources: {
        Row: {
          created_at: string
          created_by: string | null
          height_px: number
          id: string
          material_selection: Json | null
          mime_type: string
          name: string
          object_path: string
          size_bytes: number
          slug: string
          status: string
          updated_at: string
          updated_by: string | null
          width_px: number
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          height_px: number
          id?: string
          material_selection?: Json | null
          mime_type: string
          name: string
          object_path: string
          size_bytes: number
          slug: string
          status?: string
          updated_at?: string
          updated_by?: string | null
          width_px: number
        }
        Update: {
          created_at?: string
          created_by?: string | null
          height_px?: number
          id?: string
          material_selection?: Json | null
          mime_type?: string
          name?: string
          object_path?: string
          size_bytes?: number
          slug?: string
          status?: string
          updated_at?: string
          updated_by?: string | null
          width_px?: number
        }
        Relationships: []
      }
      media_assets: {
        Row: {
          alt: string | null
          archived_at: string | null
          bucket: string | null
          caption: string | null
          created_at: string
          created_by: string | null
          credit: string | null
          height_px: number | null
          id: number
          media_type: string
          mime_type: string | null
          object_path: string | null
          published_at: string | null
          size_bytes: number | null
          source_kind: string
          source_url: string | null
          status: string
          updated_at: string
          updated_by: string | null
          usage_notes: string | null
          width_px: number | null
        }
        Insert: {
          alt?: string | null
          archived_at?: string | null
          bucket?: string | null
          caption?: string | null
          created_at?: string
          created_by?: string | null
          credit?: string | null
          height_px?: number | null
          id?: never
          media_type: string
          mime_type?: string | null
          object_path?: string | null
          published_at?: string | null
          size_bytes?: number | null
          source_kind?: string
          source_url?: string | null
          status?: string
          updated_at?: string
          updated_by?: string | null
          usage_notes?: string | null
          width_px?: number | null
        }
        Update: {
          alt?: string | null
          archived_at?: string | null
          bucket?: string | null
          caption?: string | null
          created_at?: string
          created_by?: string | null
          credit?: string | null
          height_px?: number | null
          id?: never
          media_type?: string
          mime_type?: string | null
          object_path?: string | null
          published_at?: string | null
          size_bytes?: number | null
          source_kind?: string
          source_url?: string | null
          status?: string
          updated_at?: string
          updated_by?: string | null
          usage_notes?: string | null
          width_px?: number | null
        }
        Relationships: []
      }
      product_material_defaults: {
        Row: {
          created_at: string
          created_by: string | null
          display_label: string | null
          id: number
          material_category: string
          material_slug: string | null
          product_id: number
          stone_group_id: number | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          display_label?: string | null
          id?: never
          material_category: string
          material_slug?: string | null
          product_id: number
          stone_group_id?: number | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          display_label?: string | null
          id?: never
          material_category?: string
          material_slug?: string | null
          product_id?: number
          stone_group_id?: number | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "product_material_defaults_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_material_defaults_stone_group_id_fkey"
            columns: ["stone_group_id"]
            isOneToOne: false
            referencedRelation: "stone_groups"
            referencedColumns: ["id"]
          },
        ]
      }
      product_models: {
        Row: {
          archived_at: string | null
          created_at: string
          created_by: string | null
          id: number
          image_media_id: number | null
          label: string
          model_key: string
          product_id: number
          published_at: string | null
          sort_order: number
          status: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          id?: never
          image_media_id?: number | null
          label: string
          model_key: string
          product_id: number
          published_at?: string | null
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          id?: never
          image_media_id?: number | null
          label?: string
          model_key?: string
          product_id?: number
          published_at?: string | null
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "product_models_image_media_id_fkey"
            columns: ["image_media_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_models_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      product_specs: {
        Row: {
          created_at: string
          created_by: string | null
          id: number
          product_id: number
          sort_order: number
          spec_label: string
          spec_value: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: never
          product_id: number
          sort_order?: number
          spec_label: string
          spec_value: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: never
          product_id?: number
          sort_order?: number
          spec_label?: string
          spec_value?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "product_specs_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          archived_at: string | null
          created_at: string
          created_by: string | null
          hero_media_id: number | null
          id: number
          name: string
          published_at: string | null
          seo: Json
          short_description: string | null
          slug: string
          sort_order: number
          status: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          hero_media_id?: number | null
          id?: never
          name: string
          published_at?: string | null
          seo?: Json
          short_description?: string | null
          slug: string
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          hero_media_id?: number | null
          id?: never
          name?: string
          published_at?: string | null
          seo?: Json
          short_description?: string | null
          slug?: string
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "products_hero_media_id_fkey"
            columns: ["hero_media_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
        ]
      }
      project_facts: {
        Row: {
          archived_at: string | null
          claim_status: string
          created_at: string
          created_by: string | null
          fact_label: string
          fact_value: string | null
          fact_value_json: Json | null
          id: number
          project_id: number
          published_at: string | null
          sort_order: number
          status: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          claim_status?: string
          created_at?: string
          created_by?: string | null
          fact_label: string
          fact_value?: string | null
          fact_value_json?: Json | null
          id?: never
          project_id: number
          published_at?: string | null
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          claim_status?: string
          created_at?: string
          created_by?: string | null
          fact_label?: string
          fact_value?: string | null
          fact_value_json?: Json | null
          id?: never
          project_id?: number
          published_at?: string | null
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "project_facts_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_hotspots: {
        Row: {
          application: string | null
          archived_at: string | null
          created_at: string
          created_by: string | null
          hotspot_key: string
          id: number
          label: string | null
          note: string | null
          preview_media_id: number | null
          project_material_id: number | null
          project_material_map_id: number
          published_at: string | null
          sort_order: number
          status: string
          updated_at: string
          updated_by: string | null
          x_percent: number
          y_percent: number
        }
        Insert: {
          application?: string | null
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          hotspot_key: string
          id?: never
          label?: string | null
          note?: string | null
          preview_media_id?: number | null
          project_material_id?: number | null
          project_material_map_id: number
          published_at?: string | null
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
          x_percent: number
          y_percent: number
        }
        Update: {
          application?: string | null
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          hotspot_key?: string
          id?: never
          label?: string | null
          note?: string | null
          preview_media_id?: number | null
          project_material_id?: number | null
          project_material_map_id?: number
          published_at?: string | null
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
          x_percent?: number
          y_percent?: number
        }
        Relationships: [
          {
            foreignKeyName: "project_hotspots_preview_media_id_fkey"
            columns: ["preview_media_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_hotspots_project_material_id_fkey"
            columns: ["project_material_id"]
            isOneToOne: false
            referencedRelation: "project_materials"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_hotspots_project_material_map_id_fkey"
            columns: ["project_material_map_id"]
            isOneToOne: false
            referencedRelation: "project_material_maps"
            referencedColumns: ["id"]
          },
        ]
      }
      project_material_maps: {
        Row: {
          archived_at: string | null
          created_at: string
          created_by: string | null
          id: number
          intro: string | null
          media_asset_id: number
          project_id: number
          published_at: string | null
          sort_order: number
          status: string
          title: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          id?: never
          intro?: string | null
          media_asset_id: number
          project_id: number
          published_at?: string | null
          sort_order?: number
          status?: string
          title?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          id?: never
          intro?: string | null
          media_asset_id?: number
          project_id?: number
          published_at?: string | null
          sort_order?: number
          status?: string
          title?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "project_material_maps_media_asset_id_fkey"
            columns: ["media_asset_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_material_maps_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_materials: {
        Row: {
          application: string
          archived_at: string | null
          claim_status: string
          created_at: string
          created_by: string | null
          finish_definition_id: number | null
          id: number
          media_asset_id: number | null
          note: string | null
          project_id: number
          published_at: string | null
          sort_order: number
          status: string
          stone_group_id: number | null
          stone_variant_id: number | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          application: string
          archived_at?: string | null
          claim_status?: string
          created_at?: string
          created_by?: string | null
          finish_definition_id?: number | null
          id?: never
          media_asset_id?: number | null
          note?: string | null
          project_id: number
          published_at?: string | null
          sort_order?: number
          status?: string
          stone_group_id?: number | null
          stone_variant_id?: number | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          application?: string
          archived_at?: string | null
          claim_status?: string
          created_at?: string
          created_by?: string | null
          finish_definition_id?: number | null
          id?: never
          media_asset_id?: number | null
          note?: string | null
          project_id?: number
          published_at?: string | null
          sort_order?: number
          status?: string
          stone_group_id?: number | null
          stone_variant_id?: number | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "project_materials_finish_definition_id_fkey"
            columns: ["finish_definition_id"]
            isOneToOne: false
            referencedRelation: "finish_definitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_materials_media_asset_id_fkey"
            columns: ["media_asset_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_materials_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_materials_stone_group_id_fkey"
            columns: ["stone_group_id"]
            isOneToOne: false
            referencedRelation: "stone_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_materials_stone_variant_id_fkey"
            columns: ["stone_variant_id"]
            isOneToOne: false
            referencedRelation: "stone_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      project_media: {
        Row: {
          archived_at: string | null
          block_title: string | null
          caption: string | null
          created_at: string
          created_by: string | null
          id: number
          label: string | null
          media_asset_id: number | null
          media_role: string
          project_id: number
          project_material_map_id: number | null
          published_at: string | null
          sort_order: number
          status: string
          updated_at: string
          updated_by: string | null
          youtube_url: string | null
        }
        Insert: {
          archived_at?: string | null
          block_title?: string | null
          caption?: string | null
          created_at?: string
          created_by?: string | null
          id?: never
          label?: string | null
          media_asset_id?: number | null
          media_role: string
          project_id: number
          project_material_map_id?: number | null
          published_at?: string | null
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
          youtube_url?: string | null
        }
        Update: {
          archived_at?: string | null
          block_title?: string | null
          caption?: string | null
          created_at?: string
          created_by?: string | null
          id?: never
          label?: string | null
          media_asset_id?: number | null
          media_role?: string
          project_id?: number
          project_material_map_id?: number | null
          published_at?: string | null
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
          youtube_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "project_media_media_asset_id_fkey"
            columns: ["media_asset_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_media_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_media_project_material_map_id_fkey"
            columns: ["project_material_map_id"]
            isOneToOne: false
            referencedRelation: "project_material_maps"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          address: string | null
          archived_at: string | null
          carbon_note: string | null
          carbon_status: string | null
          claim_review_status: string
          client: string | null
          completed_on: string | null
          contractor: string | null
          cover_media_id: number | null
          created_at: string
          created_by: string | null
          hero_media_id: number | null
          id: number
          landscape_architect: string | null
          lead: string | null
          location: string | null
          project_date_label: string | null
          published_at: string | null
          quantity_label: string | null
          seo: Json
          slug: string
          sort_order: number
          status: string
          summary: string | null
          title: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          address?: string | null
          archived_at?: string | null
          carbon_note?: string | null
          carbon_status?: string | null
          claim_review_status?: string
          client?: string | null
          completed_on?: string | null
          contractor?: string | null
          cover_media_id?: number | null
          created_at?: string
          created_by?: string | null
          hero_media_id?: number | null
          id?: never
          landscape_architect?: string | null
          lead?: string | null
          location?: string | null
          project_date_label?: string | null
          published_at?: string | null
          quantity_label?: string | null
          seo?: Json
          slug: string
          sort_order?: number
          status?: string
          summary?: string | null
          title: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          address?: string | null
          archived_at?: string | null
          carbon_note?: string | null
          carbon_status?: string | null
          claim_review_status?: string
          client?: string | null
          completed_on?: string | null
          contractor?: string | null
          cover_media_id?: number | null
          created_at?: string
          created_by?: string | null
          hero_media_id?: number | null
          id?: never
          landscape_architect?: string | null
          lead?: string | null
          location?: string | null
          project_date_label?: string | null
          published_at?: string | null
          quantity_label?: string | null
          seo?: Json
          slug?: string
          sort_order?: number
          status?: string
          summary?: string | null
          title?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "projects_cover_media_id_fkey"
            columns: ["cover_media_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "projects_hero_media_id_fkey"
            columns: ["hero_media_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
        ]
      }
      sample_request_items: {
        Row: {
          created_at: string
          finish_definition_id: number | null
          id: number
          notes: string | null
          quantity: number
          sample_request_id: number
          stone_group_id: number | null
        }
        Insert: {
          created_at?: string
          finish_definition_id?: number | null
          id?: never
          notes?: string | null
          quantity?: number
          sample_request_id: number
          stone_group_id?: number | null
        }
        Update: {
          created_at?: string
          finish_definition_id?: number | null
          id?: never
          notes?: string | null
          quantity?: number
          sample_request_id?: number
          stone_group_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "sample_request_items_finish_definition_id_fkey"
            columns: ["finish_definition_id"]
            isOneToOne: false
            referencedRelation: "finish_definitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sample_request_items_sample_request_id_fkey"
            columns: ["sample_request_id"]
            isOneToOne: false
            referencedRelation: "sample_requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sample_request_items_stone_group_id_fkey"
            columns: ["stone_group_id"]
            isOneToOne: false
            referencedRelation: "stone_groups"
            referencedColumns: ["id"]
          },
        ]
      }
      sample_requests: {
        Row: {
          assigned_to: string | null
          company: string | null
          created_at: string
          email: string
          id: number
          internal_notes: string | null
          message: string | null
          name: string
          notification_status: string
          phone: string | null
          project_name: string | null
          shipping_address: string | null
          source_route: string | null
          status: string
          turnstile_success: boolean | null
          updated_at: string
        }
        Insert: {
          assigned_to?: string | null
          company?: string | null
          created_at?: string
          email: string
          id?: never
          internal_notes?: string | null
          message?: string | null
          name: string
          notification_status?: string
          phone?: string | null
          project_name?: string | null
          shipping_address?: string | null
          source_route?: string | null
          status?: string
          turnstile_success?: boolean | null
          updated_at?: string
        }
        Update: {
          assigned_to?: string | null
          company?: string | null
          created_at?: string
          email?: string
          id?: never
          internal_notes?: string | null
          message?: string | null
          name?: string
          notification_status?: string
          phone?: string | null
          project_name?: string | null
          shipping_address?: string | null
          source_route?: string | null
          status?: string
          turnstile_success?: boolean | null
          updated_at?: string
        }
        Relationships: []
      }
      site_settings: {
        Row: {
          archived_at: string | null
          company_name: string
          created_at: string
          created_by: string | null
          default_share_media_id: number | null
          favicon_media_id: number | null
          footer_columns: Json
          id: number
          logo_media_id: number | null
          primary_email: string | null
          primary_phone: string | null
          published_at: string | null
          seo: Json
          settings_key: string
          social_links: Json
          status: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          company_name?: string
          created_at?: string
          created_by?: string | null
          default_share_media_id?: number | null
          favicon_media_id?: number | null
          footer_columns?: Json
          id?: never
          logo_media_id?: number | null
          primary_email?: string | null
          primary_phone?: string | null
          published_at?: string | null
          seo?: Json
          settings_key: string
          social_links?: Json
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          company_name?: string
          created_at?: string
          created_by?: string | null
          default_share_media_id?: number | null
          favicon_media_id?: number | null
          footer_columns?: Json
          id?: never
          logo_media_id?: number | null
          primary_email?: string | null
          primary_phone?: string | null
          published_at?: string | null
          seo?: Json
          settings_key?: string
          social_links?: Json
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "site_settings_default_share_media_id_fkey"
            columns: ["default_share_media_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "site_settings_favicon_media_id_fkey"
            columns: ["favicon_media_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "site_settings_logo_media_id_fkey"
            columns: ["logo_media_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
        ]
      }
      stone_availability_options: {
        Row: {
          archived_at: string | null
          created_at: string
          created_by: string | null
          display_name: string
          id: number
          option_key: string
          sort_order: number
          status: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          display_name: string
          id?: never
          option_key: string
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          display_name?: string
          id?: never
          option_key?: string
          sort_order?: number
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      stone_finish_capabilities: {
        Row: {
          admin_note: string | null
          archived_at: string | null
          behavior_note: string | null
          capability: string
          created_at: string
          created_by: string | null
          finish_definition_id: number
          id: number
          published_at: string | null
          sources: string[]
          stone_variant_id: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          admin_note?: string | null
          archived_at?: string | null
          behavior_note?: string | null
          capability: string
          created_at?: string
          created_by?: string | null
          finish_definition_id: number
          id?: never
          published_at?: string | null
          sources?: string[]
          stone_variant_id: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          admin_note?: string | null
          archived_at?: string | null
          behavior_note?: string | null
          capability?: string
          created_at?: string
          created_by?: string | null
          finish_definition_id?: number
          id?: never
          published_at?: string | null
          sources?: string[]
          stone_variant_id?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "stone_finish_capabilities_finish_definition_id_fkey"
            columns: ["finish_definition_id"]
            isOneToOne: false
            referencedRelation: "finish_definitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stone_finish_capabilities_stone_variant_id_fkey"
            columns: ["stone_variant_id"]
            isOneToOne: false
            referencedRelation: "stone_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      stone_finish_images: {
        Row: {
          archived_at: string | null
          created_at: string
          created_by: string | null
          finish_definition_id: number | null
          id: number
          image_role: string
          media_asset_id: number
          published_at: string | null
          sort_order: number
          status: string
          stone_group_id: number | null
          stone_variant_id: number | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          finish_definition_id?: number | null
          id?: never
          image_role?: string
          media_asset_id: number
          published_at?: string | null
          sort_order?: number
          status?: string
          stone_group_id?: number | null
          stone_variant_id?: number | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          finish_definition_id?: number | null
          id?: never
          image_role?: string
          media_asset_id?: number
          published_at?: string | null
          sort_order?: number
          status?: string
          stone_group_id?: number | null
          stone_variant_id?: number | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "stone_finish_images_finish_definition_id_fkey"
            columns: ["finish_definition_id"]
            isOneToOne: false
            referencedRelation: "finish_definitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stone_finish_images_media_asset_id_fkey"
            columns: ["media_asset_id"]
            isOneToOne: false
            referencedRelation: "media_assets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stone_finish_images_stone_group_id_fkey"
            columns: ["stone_group_id"]
            isOneToOne: false
            referencedRelation: "stone_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stone_finish_images_stone_variant_id_fkey"
            columns: ["stone_variant_id"]
            isOneToOne: false
            referencedRelation: "stone_variants"
            referencedColumns: ["id"]
          },
        ]
      }
      stone_groups: {
        Row: {
          archived_at: string | null
          availability_status: string
          available_as: string[]
          catalog_managed: boolean
          created_at: string
          created_by: string | null
          cut_options: Json
          display_name: string
          id: number
          notes: string | null
          origin_country: string | null
          origin_region: string | null
          price_source: string | null
          price_tier: number | null
          published_at: string | null
          raw_block_height_mm: number | null
          raw_block_length_mm: number | null
          raw_block_width_mm: number | null
          sort_order: number
          source_name: string | null
          status: string
          stone_group_key: string
          stone_type_display: string | null
          stone_type_source: string | null
          summary: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          availability_status?: string
          available_as?: string[]
          catalog_managed?: boolean
          created_at?: string
          created_by?: string | null
          cut_options?: Json
          display_name: string
          id?: never
          notes?: string | null
          origin_country?: string | null
          origin_region?: string | null
          price_source?: string | null
          price_tier?: number | null
          published_at?: string | null
          raw_block_height_mm?: number | null
          raw_block_length_mm?: number | null
          raw_block_width_mm?: number | null
          sort_order?: number
          source_name?: string | null
          status?: string
          stone_group_key: string
          stone_type_display?: string | null
          stone_type_source?: string | null
          summary?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          availability_status?: string
          available_as?: string[]
          catalog_managed?: boolean
          created_at?: string
          created_by?: string | null
          cut_options?: Json
          display_name?: string
          id?: never
          notes?: string | null
          origin_country?: string | null
          origin_region?: string | null
          price_source?: string | null
          price_tier?: number | null
          published_at?: string | null
          raw_block_height_mm?: number | null
          raw_block_length_mm?: number | null
          raw_block_width_mm?: number | null
          sort_order?: number
          source_name?: string | null
          status?: string
          stone_group_key?: string
          stone_type_display?: string | null
          stone_type_source?: string | null
          summary?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      stone_variants: {
        Row: {
          archived_at: string | null
          created_at: string
          created_by: string | null
          display_name: string | null
          id: number
          published_at: string | null
          sort_order: number
          source_variant: string | null
          status: string
          stone_group_id: number
          updated_at: string
          updated_by: string | null
          variant_key: string
          variant_type: string
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          display_name?: string | null
          id?: never
          published_at?: string | null
          sort_order?: number
          source_variant?: string | null
          status?: string
          stone_group_id: number
          updated_at?: string
          updated_by?: string | null
          variant_key: string
          variant_type?: string
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          display_name?: string | null
          id?: never
          published_at?: string | null
          sort_order?: number
          source_variant?: string | null
          status?: string
          stone_group_id?: number
          updated_at?: string
          updated_by?: string | null
          variant_key?: string
          variant_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "stone_variants_stone_group_id_fkey"
            columns: ["stone_group_id"]
            isOneToOne: false
            referencedRelation: "stone_groups"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_project_aggregate: {
        Args: {
          p_action: string
          p_actor_user_id: string
          p_base_revision: number
          p_base_updated_at: string
          p_draft: Json
          p_expected_actor_role: string
          p_project_id: number
          p_promotions: Json
        }
        Returns: Json
      }
      admin_stone_availability_options: {
        Args: {
          p_action: string
          p_actor: string
          p_option?: Json
          p_request_id: string
          p_role: string
        }
        Returns: Json
      }
      admin_stone_workspace: {
        Args: {
          p_action: string
          p_actor: string
          p_draft: Json
          p_live_version: string
          p_promotions?: Json
          p_request_id: string
          p_revision: number
          p_role: string
          p_stone_id: number
        }
        Returns: Json
      }
      current_admin_role: { Args: never; Returns: string }
      get_archived_project_slugs: {
        Args: never
        Returns: {
          slug: string
        }[]
      }
      has_admin_role: { Args: { allowed_roles: string[] }; Returns: boolean }
      public_stone_catalogue: { Args: never; Returns: Json }
      submit_sample_request_with_item: {
        Args: { p_item: Json; p_request: Json }
        Returns: {
          sample_request_id: number
          sample_request_item_id: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
