import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';

export const generatedPaths = ['docs/HANDOFF.md', 'docs/NEXT_STEPS.md'];
export function loadState(root = process.cwd()) {
  const read = (path) => JSON.parse(readFileSync(join(root, path), 'utf8'));
  return { status: read('docs/agent/status.json'), queue: read('docs/agent/tasks.json'), modules: read('docs/agent/modules.json') };
}
const cell = (value) => String(value ?? '').replace(/\|/g, '\\|').replace(/[\r\n]+/g, ' ');
export function renderState({ status, queue }) {
  const current = queue.tasks.find((task) => task.id === status.currentTaskId);
  const intro = `<!-- Generated by npm run agent:state. Edit status.json/tasks.json, not this file. -->\n\nLast updated: ${status.lastUpdated}\n`;
  const release = `## 已观察的发布状态\n\n观察日期：${status.release.observedAt}。仓库版本：\`${status.release.repositorySha}\`。已验证运行时代码：\`${status.release.runtimeSha}\`。\n\n验证地址：${status.release.verifiedRuntimeUrl}\n\n${status.release.note}\n\nCMS handoff: **${status.production.adminCmsHandoff}**。QR: ${status.production.qr}。\n`;
  const blockers = status.externalDependencies.map((item) => `- **${item.id} / ${item.status}**：${cell(item.detail)}`).join('\n');
  const handoff = `# 当前任务与交接\n\n${intro}\n## 正在执行\n\n**${current?.id ?? 'none'}** — ${current?.summary ?? 'No active task'}\n\n阶段：${current?.phase ?? 'none'}。状态：${current?.status ?? 'none'}。\n\n${release}\n## 外部依赖\n\n${blockers}\n\n## 接手入口\n\n运行 \`npm run agent:init\`，只读当前任务及列出的模块规则。\`docs/agent/status.json\` 是发布观察来源，\`docs/agent/tasks.json\` 是任务来源。历史索引在 \`docs/WORKLOG.md\`。\n`;
  const tasks = [...queue.tasks].sort((a, b) => a.priority - b.priority);
  const overview = `# 项目执行总览\n\n${intro}\n## 任务\n\n| ID | 状态 / 阶段 | 内容 | 阻塞 |\n|---|---|---|---|\n${tasks.map((task) => `| ${task.id} | ${task.status} / ${task.phase} | ${cell(task.summary)} | ${cell(task.blocker || '—')} |`).join('\n')}\n\n已完成任务归档：\`${queue.archive}\`。本表不把等待客户验收当作代码开发。\n`;
  const readme = `<!-- agent:status:start -->\n## Current status\n\nObserved ${status.release.observedAt}: public site **${status.production.site}**, QR **${status.production.qr}**, CMS handoff **${status.production.adminCmsHandoff}**.\n\nCurrent task: **${status.currentTaskId}**. See [handoff](docs/HANDOFF.md), [task overview](docs/NEXT_STEPS.md) and [project map](docs/PROJECT_MAP.md). These summaries are generated from repository-owned state.\n<!-- agent:status:end -->`;
  return { 'docs/HANDOFF.md': handoff, 'docs/NEXT_STEPS.md': overview, readme };
}

export function validateState(bundle, root = process.cwd()) {
  const errors = [];
  const { status, queue, modules } = bundle;
  if (status.version !== 2 || queue.version !== 2) errors.push('State and queue must use version 2.');
  if (!Array.isArray(queue.tasks)) return ['tasks must be an array'];
  const ids = new Set();
  for (const task of queue.tasks) {
    if (!task.id || ids.has(task.id)) errors.push(`Missing or duplicate task ID: ${task.id}`);
    ids.add(task.id);
    if (!['now', 'next', 'later', 'blocked'].includes(task.status)) errors.push(`Archive completed or invalid task: ${task.id}`);
    if (!['planned', 'implementation', 'verification', 'awaiting_external', 'release'].includes(task.phase)) errors.push(`Invalid task phase: ${task.id}`);
    if (task.status === 'blocked' && !task.blocker) errors.push(`Blocked task has no reason: ${task.id}`);
    if (!Number.isFinite(task.priority) || !task.summary || !Array.isArray(task.acceptance) || !Array.isArray(task.verification)) errors.push(`Incomplete task: ${task.id}`);
    for (const id of task.modules || []) if (!modules.modules[id]) errors.push(`Unknown module ${id} in ${task.id}`);
    if (task.authorization && !task.authorization.source) errors.push(`Authorization has no user source: ${task.id}`);
  }
  const current = queue.tasks.find((task) => task.id === status.currentTaskId);
  if (!current || !['now', 'blocked'].includes(current.status)) errors.push('currentTaskId must reference a current or explicitly blocked task.');
  for (const key of ['repositorySha', 'runtimeSha']) if (!/^[a-f0-9]{40}$/.test(status.release?.[key] || '')) errors.push(`Invalid ${key}`);
  if (!/^https:\/\/[a-f0-9]{8}\.urblo(?:-site)?\.pages\.dev$/.test(status.release?.verifiedRuntimeUrl || '')) errors.push('Release requires an immutable runtime URL.');
  if (status.environments?.preview?.dataTarget === 'production' && status.environments.preview.testPolicy !== 'read_only') errors.push('Shared production Preview must be read_only.');
  const cms = JSON.parse(readFileSync(join(root, 'docs/agent/admin-handoff-evidence.json'), 'utf8'));
  if (status.production.adminCmsHandoff !== cms.state) errors.push('CMS status contradicts structured production handoff evidence.');
  for (const [id, module] of Object.entries(modules.modules)) for (const path of [...module.paths, ...module.rules]) if (!existsSync(join(root, path))) errors.push(`Module ${id} has missing path ${path}`);
  const archive = JSON.parse(readFileSync(join(root, queue.archive), 'utf8'));
  for (const task of archive.tasks) if (ids.has(task.id)) errors.push(`Task ${task.id} appears in active and completed queues.`);
  let startupBytes = 0;
  for (const path of status.startup.files) startupBytes += readFileSync(join(root, path)).length;
  if (readFileSync(join(root, 'AGENTS.md')).length > status.startup.maxAgentsBytes) errors.push('AGENTS exceeds byte budget.');
  if (startupBytes > status.startup.maxTotalBytes) errors.push(`Startup exceeds byte budget: ${startupBytes}`);
  return errors;
}

export function checkGenerated(bundle, root = process.cwd()) {
  const rendered = renderState(bundle);
  const errors = generatedPaths.filter((path) => readFileSync(join(root, path), 'utf8') !== rendered[path]).map((path) => `${path} is stale; regenerate state.`);
  const readme = readFileSync(join(root, 'README.md'), 'utf8');
  if (readme.match(/<!-- agent:status:start -->[\s\S]*?<!-- agent:status:end -->/)?.[0] !== rendered.readme) errors.push('README state is stale or contradictory.');
  const outsideStatus = readme.replace(/<!-- agent:status:start -->[\s\S]*?<!-- agent:status:end -->/, '');
  if (bundle.status.production.adminCmsHandoff !== 'verified' && /(?:handoff.{0,50}(?:passed|complete)|(?:passed|complete).{0,50}handoff)/i.test(outsideStatus)) errors.push('README claims an unverified CMS handoff.');
  return errors;
}

export function verifyArchive(root = process.cwd()) {
  const manifest = JSON.parse(readFileSync(join(root, 'docs/archive/2026-09-09/worklog-index.json'), 'utf8'));
  const chunks = manifest.parts.map((part) => readFileSync(join(root, part.path)));
  const sha = (data) => createHash('sha256').update(data).digest('hex');
  const errors = manifest.parts.flatMap((part, index) => sha(chunks[index]) === part.sha256 ? [] : [`Historical archive modified: ${part.path}`]);
  if (sha(Buffer.concat(chunks)) !== manifest.originalSha256) errors.push('Historical WORKLOG no longer reproduces original bytes.');
  return errors;
}
